name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -project 'Numero.xcodeproj' -scheme 'Numero' -detination 'generic/platform=iOS' -configutation Release build CODE_SIGNING_ALLOWED=NO
    - name: Run tests
      run: xcodebuild -project 'Numero.xcodeproj' -scheme 'Numero' -detination 'platform=iOS Simulator,name=iPhone 8' test
